// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AestheticScorePublic
 */
export type AestheticScorePublic = {
    scorer: string;
    score: number;
};

/**
 * CountPostsResponse
 */
export type CountPostsResponse = {
    count: number;
};

/**
 * CursorResponse
 */
export type CursorResponse = {
    items: Array<{
        [key: string]: unknown;
    }>;
    nextCursor?: number | null;
};

/**
 * DanbooruDownloadStats
 */
export type DanbooruDownloadStats = {
    total: number;
    with_url: number;
    filtered: number;
    downloaded: number;
    skipped: number;
    failed: number;
};

/**
 * DirectorySummary
 */
export type DirectorySummary = {
    name: string;
    path: string;
    file_count: number;
    post_count?: number;
    silva_avg?: number | null;
    score_avg?: number | null;
    rating_avg?: number | null;
    scored_ratio?: number | null;
    children?: Array<DirectorySummary>;
};

/**
 * ExtensionCountItem
 */
export type ExtensionCountItem = {
    extension: string;
    count: number;
};

/**
 * GalleryDLStats
 */
export type GalleryDlStats = {
    fetched?: number;
    images?: number;
    new?: number;
    downloaded?: number;
    failed?: number;
};

/**
 * UploadFormData
 */
export type PostControllerUploadFormData = {
    url?: string | null;
    path?: string | null;
    source?: string | null;
    file: Blob | File;
};

/**
 * PostDetailPublic
 */
export type PostDetailPublic = {
    id: number;
    filePath: string;
    fileName: string;
    extension: string;
    fullPath: string;
    width?: number | null;
    height?: number | null;
    aspectRatio?: number | null;
    updatedAt: string;
    createdAt: string;
    score: number;
    rating: number;
    description: string;
    meta: string;
    sha256: string;
    size: number;
    source: string;
    caption: string;
    colors: Array<PostHasColorPublic>;
    publishedAt?: string | null;
    dominantColor?: Array<number> | null;
    arthash?: string | null;
    canonicalPostId?: number | null;
    groupMemberCount?: number;
    waifuScore?: WaifuScorePublic | null;
    aestheticScores?: Array<AestheticScorePublic>;
    tags: Array<PostHasTagPublic>;
};

/**
 * PostFilter
 */
export type PostFilter = {
    /**
     * Rating filter.
     */
    rating?: Array<number> | null;
    /**
     * Score filter.
     */
    score?: Array<number> | null;
    /**
     * Tag filter.
     */
    tags?: Array<string> | null;
    /**
     * Extension filter.
     */
    extension?: Array<string> | null;
    folder?: string | null;
    /**
     * LAB color filter.
     */
    lab?: [
        number,
        number,
        number
    ] | null;
    /**
     * Waifu score range filter.
     */
    waifu_score_range?: [
        number,
        number
    ] | null;
    /**
     * Waifu-score bucket filter. Each value is one of 'A' (8-10), 'B' (6-8), 'C' (4-6), 'D' (2-4), 'E' (0-2), or 'UNSCORED' (no waifu score yet). Multiple values OR together.
     */
    waifu_score_levels?: Array<string> | null;
    /**
     * SILVA aesthetic bucket filter. Each value is one of 'A' (0.8-1.0), 'B' (0.6-0.8), 'C' (0.4-0.6), 'D' (0.2-0.4), 'E' (0-0.2), or 'UNSCORED' (no SILVA score yet). OR together.
     */
    silva_score_levels?: Array<string> | null;
    /**
     * When true (default), hide near-duplicate group *members* and return only canonical (representative) posts — those with canonical_post_id NULL. Set false to include members.
     */
    only_canonical?: boolean;
};

/**
 * PostFilterWithOrder
 */
export type PostFilterWithOrder = {
    /**
     * Rating filter.
     */
    rating?: Array<number> | null;
    /**
     * Score filter.
     */
    score?: Array<number> | null;
    /**
     * Tag filter.
     */
    tags?: Array<string> | null;
    /**
     * Extension filter.
     */
    extension?: Array<string> | null;
    folder?: string | null;
    /**
     * LAB color filter.
     */
    lab?: [
        number,
        number,
        number
    ] | null;
    /**
     * Waifu score range filter.
     */
    waifu_score_range?: [
        number,
        number
    ] | null;
    /**
     * Waifu-score bucket filter. Each value is one of 'A' (8-10), 'B' (6-8), 'C' (4-6), 'D' (2-4), 'E' (0-2), or 'UNSCORED' (no waifu score yet). Multiple values OR together.
     */
    waifu_score_levels?: Array<string> | null;
    /**
     * SILVA aesthetic bucket filter. Each value is one of 'A' (0.8-1.0), 'B' (0.6-0.8), 'C' (0.4-0.6), 'D' (0.2-0.4), 'E' (0-0.2), or 'UNSCORED' (no SILVA score yet). OR together.
     */
    silva_score_levels?: Array<string> | null;
    /**
     * When true (default), hide near-duplicate group *members* and return only canonical (representative) posts — those with canonical_post_id NULL. Set false to include members.
     */
    only_canonical?: boolean;
    /**
     * Order column.
     */
    order_by?: 'id' | 'score' | 'rating' | 'created_at' | 'published_at' | 'file_name' | 'last_accessed_at' | 'updated_at' | 'waifu_score' | 'silva_score' | null;
    /**
     * Order direction.
     */
    order?: 'asc' | 'desc' | 'random';
    /**
     * Seed for ``order='random'``. The same seed yields a stable shuffle, so offset pagination stays consistent across pages; a fresh seed reshuffles. Ignored unless ``order='random'``.
     */
    order_seed?: number | null;
    /**
     * Sort direction for ``order_by`` when ``order='random'``. Ignored unless both ``order='random'`` and ``order_by`` are set.
     */
    sort_direction?: 'asc' | 'desc' | null;
};

/**
 * PostHasColorPublic
 */
export type PostHasColorPublic = {
    order: number;
    color: number;
};

/**
 * PostHasTagPublic
 */
export type PostHasTagPublic = {
    isAuto: boolean;
    tagInfo: TagWithGroupPublic;
};

/**
 * PostSimplePublic
 */
export type PostSimplePublic = {
    id: number;
    filePath: string;
    fileName: string;
    extension: string;
    rating: number;
    score: number;
    size: number;
    width: number;
    height: number;
    aspectRatio?: number | null;
    dominantColor?: Array<number> | null;
    arthash?: string | null;
    colors: Array<PostHasColorPublic>;
    sha256: string;
    canonicalPostId?: number | null;
    groupMemberCount?: number;
    matchProb?: number | null;
};

/**
 * PostStatsResponse
 */
export type PostStatsResponse = {
    total: number;
    avgScore?: number | null;
    scoredCount: number;
    avgWaifuScore?: number | null;
    waifuCount: number;
    ratingDistribution: Array<RatingCountItem>;
};

/**
 * RatingCountItem
 */
export type RatingCountItem = {
    rating: number;
    count: number;
};

/**
 * Result
 */
export type Result = {
    msg: string;
};

/**
 * ScoreCountItem
 */
export type ScoreCountItem = {
    score: number;
    count: number;
};

/**
 * ScoreUpdate
 */
export type ScoreUpdate = {
    /**
     * Score from 0 to 5.
     */
    score: number;
};

/**
 * SilvaBucketCountItem
 */
export type SilvaBucketCountItem = {
    bucket: string;
    count: number;
};

/**
 * SnapshotResult
 */
export type SnapshotResult = {
    path: string;
    dir: string;
};

/**
 * TagBatchDelete
 */
export type TagBatchDelete = {
    name_list: Array<string>;
};

/**
 * TagCountItem
 */
export type TagCountItem = {
    tag_name: string;
    count: number;
    translated_name?: string | null;
};

/**
 * TagCountRequest
 */
export type TagCountRequest = {
    /**
     * Rating filter.
     */
    rating?: Array<number> | null;
    /**
     * Score filter.
     */
    score?: Array<number> | null;
    /**
     * Tag filter.
     */
    tags?: Array<string> | null;
    /**
     * Extension filter.
     */
    extension?: Array<string> | null;
    folder?: string | null;
    /**
     * LAB color filter.
     */
    lab?: [
        number,
        number,
        number
    ] | null;
    /**
     * Waifu score range filter.
     */
    waifu_score_range?: [
        number,
        number
    ] | null;
    /**
     * Waifu-score bucket filter. Each value is one of 'A' (8-10), 'B' (6-8), 'C' (4-6), 'D' (2-4), 'E' (0-2), or 'UNSCORED' (no waifu score yet). Multiple values OR together.
     */
    waifu_score_levels?: Array<string> | null;
    /**
     * SILVA aesthetic bucket filter. Each value is one of 'A' (0.8-1.0), 'B' (0.6-0.8), 'C' (0.4-0.6), 'D' (0.2-0.4), 'E' (0-0.2), or 'UNSCORED' (no SILVA score yet). OR together.
     */
    silva_score_levels?: Array<string> | null;
    /**
     * When true (default), hide near-duplicate group *members* and return only canonical (representative) posts — those with canonical_post_id NULL. Set false to include members.
     */
    only_canonical?: boolean;
    /**
     * Substring filter on tag names.
     */
    query?: string;
    /**
     * Max tags returned, by descending count.
     */
    limit?: number;
};

/**
 * TagCreate
 */
export type TagCreate = {
    name: string;
    group_id?: number | null;
};

/**
 * TagGroupPublic
 */
export type TagGroupPublic = {
    id: number;
    name: string;
    color: string;
};

/**
 * TagPublic
 */
export type TagPublic = {
    name: string;
    group?: TagGroupPublic | null;
    translatedName?: string | null;
};

/**
 * TagUpdate
 */
export type TagUpdate = {
    group_id?: number | null;
};

/**
 * TagWithCountPublic
 */
export type TagWithCountPublic = {
    name: string;
    group?: TagGroupPublic | null;
    translatedName?: string | null;
    count: number;
};

/**
 * TagWithGroupPublic
 */
export type TagWithGroupPublic = {
    group?: TagGroupPublic | null;
    name: string;
    translatedName?: string | null;
    updatedAt: string;
    createdAt: string;
};

/**
 * TextSearchRequest
 */
export type TextSearchRequest = {
    /**
     * Rating filter.
     */
    rating?: Array<number> | null;
    /**
     * Score filter.
     */
    score?: Array<number> | null;
    /**
     * Tag filter.
     */
    tags?: Array<string> | null;
    /**
     * Extension filter.
     */
    extension?: Array<string> | null;
    folder?: string | null;
    /**
     * LAB color filter.
     */
    lab?: [
        number,
        number,
        number
    ] | null;
    /**
     * Waifu score range filter.
     */
    waifu_score_range?: [
        number,
        number
    ] | null;
    /**
     * Waifu-score bucket filter. Each value is one of 'A' (8-10), 'B' (6-8), 'C' (4-6), 'D' (2-4), 'E' (0-2), or 'UNSCORED' (no waifu score yet). Multiple values OR together.
     */
    waifu_score_levels?: Array<string> | null;
    /**
     * SILVA aesthetic bucket filter. Each value is one of 'A' (0.8-1.0), 'B' (0.6-0.8), 'C' (0.4-0.6), 'D' (0.2-0.4), 'E' (0-0.2), or 'UNSCORED' (no SILVA score yet). OR together.
     */
    silva_score_levels?: Array<string> | null;
    /**
     * When true (default), hide near-duplicate group *members* and return only canonical (representative) posts — those with canonical_post_id NULL. Set false to include members.
     */
    only_canonical?: boolean;
    /**
     * Natural-language search prompt.
     */
    query?: string;
};

/**
 * UrlImportStatus
 */
export type UrlImportStatus = {
    state?: 'idle' | 'running' | 'done' | 'failed';
    url?: string | null;
    stats?: GalleryDlStats | null;
    error?: string | null;
    startedAt?: string | null;
    finishedAt?: string | null;
    syncTriggered?: boolean;
};

/**
 * WaifuBucketCountItem
 */
export type WaifuBucketCountItem = {
    bucket: string;
    count: number;
};

/**
 * WaifuScorePublic
 */
export type WaifuScorePublic = {
    score: number;
};

/**
 * WaifuScoreResult
 */
export type WaifuScoreResult = {
    bucket: string;
    count: number;
};

export type V2RemoveTagFromPostData = {
    body?: never;
    path: {
        post_id: number;
        tag_name: string;
    };
    query?: never;
    url: '/v2/posts/{post_id}/tags/{tag_name}';
};

export type V2RemoveTagFromPostErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2RemoveTagFromPostError = V2RemoveTagFromPostErrors[keyof V2RemoveTagFromPostErrors];

export type V2RemoveTagFromPostResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2RemoveTagFromPostResponse = V2RemoveTagFromPostResponses[keyof V2RemoveTagFromPostResponses];

export type V2AddTagToPostData = {
    body?: never;
    path: {
        post_id: number;
        tag_name: string;
    };
    query?: never;
    url: '/v2/posts/{post_id}/tags/{tag_name}';
};

export type V2AddTagToPostErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2AddTagToPostError = V2AddTagToPostErrors[keyof V2AddTagToPostErrors];

export type V2AddTagToPostResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2AddTagToPostResponse = V2AddTagToPostResponses[keyof V2AddTagToPostResponses];

export type V2BulkUpdatePostRatingData = {
    body?: never;
    path?: never;
    query: {
        ids: Array<number>;
        rating: number;
    };
    url: '/v2/posts/bulk/rating';
};

export type V2BulkUpdatePostRatingErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2BulkUpdatePostRatingError = V2BulkUpdatePostRatingErrors[keyof V2BulkUpdatePostRatingErrors];

export type V2BulkUpdatePostRatingResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type V2BulkUpdatePostScoreData = {
    body?: never;
    path?: never;
    query: {
        ids: Array<number>;
        score: number;
    };
    url: '/v2/posts/bulk/score';
};

export type V2BulkUpdatePostScoreErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2BulkUpdatePostScoreError = V2BulkUpdatePostScoreErrors[keyof V2BulkUpdatePostScoreErrors];

export type V2BulkUpdatePostScoreResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type V2DeletePostsData = {
    body?: never;
    path?: never;
    query: {
        ids: Array<number>;
    };
    url: '/v2/posts/delete';
};

export type V2DeletePostsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2DeletePostsError = V2DeletePostsErrors[keyof V2DeletePostsErrors];

export type V2DeletePostsResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type V2DeletePostsResponse = V2DeletePostsResponses[keyof V2DeletePostsResponses];

export type V2GetExtensionCountData = {
    body: PostFilter;
    path?: never;
    query?: never;
    url: '/v2/posts/count/extension';
};

export type V2GetExtensionCountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetExtensionCountError = V2GetExtensionCountErrors[keyof V2GetExtensionCountErrors];

export type V2GetExtensionCountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ExtensionCountItem>;
};

export type V2GetExtensionCountResponse = V2GetExtensionCountResponses[keyof V2GetExtensionCountResponses];

export type V2GetPostData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/posts/{post_id}';
};

export type V2GetPostErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetPostError = V2GetPostErrors[keyof V2GetPostErrors];

export type V2GetPostResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2GetPostResponse = V2GetPostResponses[keyof V2GetPostResponses];

export type V2GetPostGroupData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/posts/{post_id}/group';
};

export type V2GetPostGroupErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetPostGroupError = V2GetPostGroupErrors[keyof V2GetPostGroupErrors];

export type V2GetPostGroupResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<PostSimplePublic>;
};

export type V2GetPostGroupResponse = V2GetPostGroupResponses[keyof V2GetPostGroupResponses];

export type V2GetPostsCountData = {
    body: PostFilter;
    path?: never;
    query?: never;
    url: '/v2/posts/count';
};

export type V2GetPostsCountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetPostsCountError = V2GetPostsCountErrors[keyof V2GetPostsCountErrors];

export type V2GetPostsCountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: CountPostsResponse;
};

export type V2GetPostsCountResponse = V2GetPostsCountResponses[keyof V2GetPostsCountResponses];

export type V2GetPostsStatsData = {
    body: PostFilter;
    path?: never;
    query?: never;
    url: '/v2/posts/stats';
};

export type V2GetPostsStatsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetPostsStatsError = V2GetPostsStatsErrors[keyof V2GetPostsStatsErrors];

export type V2GetPostsStatsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostStatsResponse;
};

export type V2GetPostsStatsResponse = V2GetPostsStatsResponses[keyof V2GetPostsStatsResponses];

export type V2GetRatingCountData = {
    body: PostFilter;
    path?: never;
    query?: never;
    url: '/v2/posts/count/rating';
};

export type V2GetRatingCountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetRatingCountError = V2GetRatingCountErrors[keyof V2GetRatingCountErrors];

export type V2GetRatingCountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<RatingCountItem>;
};

export type V2GetRatingCountResponse = V2GetRatingCountResponses[keyof V2GetRatingCountResponses];

export type V2GetScoreCountData = {
    body: PostFilter;
    path?: never;
    query?: never;
    url: '/v2/posts/count/score';
};

export type V2GetScoreCountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetScoreCountError = V2GetScoreCountErrors[keyof V2GetScoreCountErrors];

export type V2GetScoreCountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ScoreCountItem>;
};

export type V2GetScoreCountResponse = V2GetScoreCountResponses[keyof V2GetScoreCountResponses];

export type V2GetSilvaBucketCountData = {
    body: PostFilter;
    path?: never;
    query?: never;
    url: '/v2/posts/count/silva';
};

export type V2GetSilvaBucketCountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetSilvaBucketCountError = V2GetSilvaBucketCountErrors[keyof V2GetSilvaBucketCountErrors];

export type V2GetSilvaBucketCountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<SilvaBucketCountItem>;
};

export type V2GetSilvaBucketCountResponse = V2GetSilvaBucketCountResponses[keyof V2GetSilvaBucketCountResponses];

export type V2GetSimilarPostsData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: {
        limit?: number;
    };
    url: '/v2/posts/{post_id}/similar';
};

export type V2GetSimilarPostsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetSimilarPostsError = V2GetSimilarPostsErrors[keyof V2GetSimilarPostsErrors];

export type V2GetSimilarPostsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<PostSimplePublic>;
};

export type V2GetSimilarPostsResponse = V2GetSimilarPostsResponses[keyof V2GetSimilarPostsResponses];

export type V2GetTagCountData = {
    body: TagCountRequest;
    path?: never;
    query?: never;
    url: '/v2/posts/count/tags';
};

export type V2GetTagCountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetTagCountError = V2GetTagCountErrors[keyof V2GetTagCountErrors];

export type V2GetTagCountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<TagCountItem>;
};

export type V2GetTagCountResponse = V2GetTagCountResponses[keyof V2GetTagCountResponses];

export type V2GetWaifuBucketCountData = {
    body: PostFilter;
    path?: never;
    query?: never;
    url: '/v2/posts/count/waifu';
};

export type V2GetWaifuBucketCountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetWaifuBucketCountError = V2GetWaifuBucketCountErrors[keyof V2GetWaifuBucketCountErrors];

export type V2GetWaifuBucketCountResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<WaifuBucketCountItem>;
};

export type V2GetWaifuBucketCountResponse = V2GetWaifuBucketCountResponses[keyof V2GetWaifuBucketCountResponses];

export type V2ListPostsData = {
    body?: never;
    path?: never;
    query?: {
        start?: number;
        limit?: number;
    };
    url: '/v2/posts';
};

export type V2ListPostsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2ListPostsError = V2ListPostsErrors[keyof V2ListPostsErrors];

export type V2ListPostsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: CursorResponse;
};

export type V2ListPostsResponse = V2ListPostsResponses[keyof V2ListPostsResponses];

export type V2MakePostCanonicalData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/posts/{post_id}/make-canonical';
};

export type V2MakePostCanonicalErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2MakePostCanonicalError = V2MakePostCanonicalErrors[keyof V2MakePostCanonicalErrors];

export type V2MakePostCanonicalResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2MakePostCanonicalResponse = V2MakePostCanonicalResponses[keyof V2MakePostCanonicalResponses];

export type V2RotatePostImageData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: {
        clockwise?: boolean;
    };
    url: '/v2/posts/{post_id}/rotate';
};

export type V2RotatePostImageErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2RotatePostImageError = V2RotatePostImageErrors[keyof V2RotatePostImageErrors];

export type V2RotatePostImageResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2RotatePostImageResponse = V2RotatePostImageResponses[keyof V2RotatePostImageResponses];

export type V2SearchPostsData = {
    body: PostFilterWithOrder;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/v2/posts/search';
};

export type V2SearchPostsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2SearchPostsError = V2SearchPostsErrors[keyof V2SearchPostsErrors];

export type V2SearchPostsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<PostSimplePublic>;
};

export type V2SearchPostsResponse = V2SearchPostsResponses[keyof V2SearchPostsResponses];

export type V2SearchPostsByTextData = {
    body: TextSearchRequest;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/v2/posts/search/text';
};

export type V2SearchPostsByTextErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2SearchPostsByTextError = V2SearchPostsByTextErrors[keyof V2SearchPostsByTextErrors];

export type V2SearchPostsByTextResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<PostSimplePublic>;
};

export type V2SearchPostsByTextResponse = V2SearchPostsByTextResponses[keyof V2SearchPostsByTextResponses];

export type V2TouchPostData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/posts/{post_id}/touch';
};

export type V2TouchPostErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2TouchPostError = V2TouchPostErrors[keyof V2TouchPostErrors];

export type V2TouchPostResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type V2TouchPostResponse = V2TouchPostResponses[keyof V2TouchPostResponses];

export type V2UngroupPostData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/posts/{post_id}/ungroup';
};

export type V2UngroupPostErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2UngroupPostError = V2UngroupPostErrors[keyof V2UngroupPostErrors];

export type V2UngroupPostResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2UngroupPostResponse = V2UngroupPostResponses[keyof V2UngroupPostResponses];

export type V2UpdatePostCaptionData = {
    body?: never;
    path: {
        post_id: number;
    };
    query: {
        caption: string;
    };
    url: '/v2/posts/{post_id}/caption';
};

export type V2UpdatePostCaptionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2UpdatePostCaptionError = V2UpdatePostCaptionErrors[keyof V2UpdatePostCaptionErrors];

export type V2UpdatePostCaptionResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2UpdatePostCaptionResponse = V2UpdatePostCaptionResponses[keyof V2UpdatePostCaptionResponses];

export type V2UpdatePostRatingData = {
    body?: never;
    path: {
        post_id: number;
    };
    query: {
        rating: number;
    };
    url: '/v2/posts/{post_id}/rating';
};

export type V2UpdatePostRatingErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2UpdatePostRatingError = V2UpdatePostRatingErrors[keyof V2UpdatePostRatingErrors];

export type V2UpdatePostRatingResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2UpdatePostRatingResponse = V2UpdatePostRatingResponses[keyof V2UpdatePostRatingResponses];

export type V2UpdatePostScoreData = {
    body: ScoreUpdate;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/posts/{post_id}/score';
};

export type V2UpdatePostScoreErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2UpdatePostScoreError = V2UpdatePostScoreErrors[keyof V2UpdatePostScoreErrors];

export type V2UpdatePostScoreResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2UpdatePostScoreResponse = V2UpdatePostScoreResponses[keyof V2UpdatePostScoreResponses];

export type V2UpdatePostSourceData = {
    body?: never;
    path: {
        post_id: number;
    };
    query: {
        source: string;
    };
    url: '/v2/posts/{post_id}/source';
};

export type V2UpdatePostSourceErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2UpdatePostSourceError = V2UpdatePostSourceErrors[keyof V2UpdatePostSourceErrors];

export type V2UpdatePostSourceResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2UpdatePostSourceResponse = V2UpdatePostSourceResponses[keyof V2UpdatePostSourceResponses];

export type V2UploadFileData = {
    body: PostControllerUploadFormData;
    path?: never;
    query?: never;
    url: '/v2/posts/upload';
};

export type V2UploadFileErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2UploadFileError = V2UploadFileErrors[keyof V2UploadFileErrors];

export type V2UploadFileResponses = {
    /**
     * Document created, URL follows
     */
    201: unknown;
};

export type V2AutoCaptionData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/cmd/auto-caption/{post_id}';
};

export type V2AutoCaptionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2AutoCaptionError = V2AutoCaptionErrors[keyof V2AutoCaptionErrors];

export type V2AutoCaptionResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2AutoCaptionResponse = V2AutoCaptionResponses[keyof V2AutoCaptionResponses];

export type V2AutoSilvaScorerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cmd/silva-scorer';
};

export type V2AutoSilvaScorerResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type V2AutoTagsData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/cmd/auto-tags/{post_id}';
};

export type V2AutoTagsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2AutoTagsError = V2AutoTagsErrors[keyof V2AutoTagsErrors];

export type V2AutoTagsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PostDetailPublic;
};

export type V2AutoTagsResponse = V2AutoTagsResponses[keyof V2AutoTagsResponses];

export type V2AutoTagsAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cmd/auto-tags';
};

export type V2AutoTagsAllResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type V2AutoWaifuScorerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cmd/waifu-scorer';
};

export type V2AutoWaifuScorerResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type V2CalculateEmbeddingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cmd/posts/embedding';
};

export type V2CalculateEmbeddingResponses = {
    /**
     * Document created, URL follows
     */
    201: Result;
};

export type V2CalculateEmbeddingResponse = V2CalculateEmbeddingResponses[keyof V2CalculateEmbeddingResponses];

export type V2DbSnapshotData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cmd/db/snapshot';
};

export type V2DbSnapshotResponses = {
    /**
     * Document created, URL follows
     */
    201: SnapshotResult;
};

export type V2DbSnapshotResponse = V2DbSnapshotResponses[keyof V2DbSnapshotResponses];

export type V2DownloadFromDanbooruData = {
    body?: never;
    path?: never;
    query: {
        tags: string;
    };
    url: '/v2/cmd/download-from-danbooru';
};

export type V2DownloadFromDanbooruErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2DownloadFromDanbooruError = V2DownloadFromDanbooruErrors[keyof V2DownloadFromDanbooruErrors];

export type V2DownloadFromDanbooruResponses = {
    /**
     * Document created, URL follows
     */
    201: DanbooruDownloadStats;
};

export type V2DownloadFromDanbooruResponse = V2DownloadFromDanbooruResponses[keyof V2DownloadFromDanbooruResponses];

export type V2GetSilvaScorerOneData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/cmd/silva-scorer/{post_id}';
};

export type V2GetSilvaScorerOneErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetSilvaScorerOneError = V2GetSilvaScorerOneErrors[keyof V2GetSilvaScorerOneErrors];

export type V2GetSilvaScorerOneResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: number;
};

export type V2GetSilvaScorerOneResponse = V2GetSilvaScorerOneResponses[keyof V2GetSilvaScorerOneResponses];

export type V2GetWaifuScorerOneData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/cmd/waifu-scorer/{post_id}';
};

export type V2GetWaifuScorerOneErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetWaifuScorerOneError = V2GetWaifuScorerOneErrors[keyof V2GetWaifuScorerOneErrors];

export type V2GetWaifuScorerOneResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: number;
};

export type V2GetWaifuScorerOneResponse = V2GetWaifuScorerOneResponses[keyof V2GetWaifuScorerOneResponses];

export type V2GroupDuplicatesData = {
    body?: never;
    path?: never;
    query?: {
        threshold?: number | null;
    };
    url: '/v2/cmd/group-duplicates';
};

export type V2GroupDuplicatesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GroupDuplicatesError = V2GroupDuplicatesErrors[keyof V2GroupDuplicatesErrors];

export type V2GroupDuplicatesResponses = {
    /**
     * Document created, URL follows
     */
    201: Result;
};

export type V2GroupDuplicatesResponse = V2GroupDuplicatesResponses[keyof V2GroupDuplicatesResponses];

export type V2ImportFromUrlEndpointData = {
    body?: never;
    path?: never;
    query: {
        url: string;
    };
    url: '/v2/cmd/import-from-url';
};

export type V2ImportFromUrlEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2ImportFromUrlEndpointError = V2ImportFromUrlEndpointErrors[keyof V2ImportFromUrlEndpointErrors];

export type V2ImportFromUrlEndpointResponses = {
    /**
     * Document created, URL follows
     */
    201: Result;
};

export type V2ImportFromUrlEndpointResponse = V2ImportFromUrlEndpointResponses[keyof V2ImportFromUrlEndpointResponses];

export type V2ImportFromUrlStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cmd/import-from-url/status';
};

export type V2ImportFromUrlStatusResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UrlImportStatus;
};

export type V2ImportFromUrlStatusResponse = V2ImportFromUrlStatusResponses[keyof V2ImportFromUrlStatusResponses];

export type V2SyncMetadataEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cmd/sync-metadata';
};

export type V2SyncMetadataEndpointResponses = {
    /**
     * Document created, URL follows
     */
    201: Result;
};

export type V2SyncMetadataEndpointResponse = V2SyncMetadataEndpointResponses[keyof V2SyncMetadataEndpointResponses];

export type V2GetOriginalData = {
    body?: never;
    path: {
        post_path: string;
    };
    query?: never;
    url: '/v2/images/original/{post_path}';
};

export type V2GetOriginalErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetOriginalError = V2GetOriginalErrors[keyof V2GetOriginalErrors];

export type V2GetOriginalResponses = {
    /**
     * File Download
     */
    200: Blob | File;
};

export type V2GetOriginalResponse = V2GetOriginalResponses[keyof V2GetOriginalResponses];

export type V2GetOriginalByIdData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/images/original/id/{post_id}';
};

export type V2GetOriginalByIdErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetOriginalByIdError = V2GetOriginalByIdErrors[keyof V2GetOriginalByIdErrors];

export type V2GetOriginalByIdResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type V2GetThumbnailData = {
    body?: never;
    path: {
        post_path: string;
    };
    query?: never;
    url: '/v2/images/thumbnails/{post_path}';
};

export type V2GetThumbnailErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetThumbnailError = V2GetThumbnailErrors[keyof V2GetThumbnailErrors];

export type V2GetThumbnailResponses = {
    /**
     * File Download
     */
    200: Blob | File;
};

export type V2GetThumbnailResponse = V2GetThumbnailResponses[keyof V2GetThumbnailResponses];

export type V2GetThumbnailByIdData = {
    body?: never;
    path: {
        post_id: number;
    };
    query?: never;
    url: '/v2/images/thumbnails/id/{post_id}';
};

export type V2GetThumbnailByIdErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2GetThumbnailByIdError = V2GetThumbnailByIdErrors[keyof V2GetThumbnailByIdErrors];

export type V2GetThumbnailByIdResponses = {
    /**
     * File Download
     */
    200: Blob | File;
};

export type V2GetThumbnailByIdResponse = V2GetThumbnailByIdResponses[keyof V2GetThumbnailByIdResponses];

export type V2DeleteTagsData = {
    body: TagBatchDelete;
    path?: never;
    query?: never;
    url: '/v2/tags';
};

export type V2DeleteTagsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2DeleteTagsError = V2DeleteTagsErrors[keyof V2DeleteTagsErrors];

export type V2DeleteTagsResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type V2DeleteTagsResponse = V2DeleteTagsResponses[keyof V2DeleteTagsResponses];

export type V2ListTagsData = {
    body?: never;
    path?: never;
    query?: {
        prev?: string | null;
        limit?: number | null;
    };
    url: '/v2/tags';
};

export type V2ListTagsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2ListTagsError = V2ListTagsErrors[keyof V2ListTagsErrors];

export type V2ListTagsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<TagWithCountPublic>;
};

export type V2ListTagsResponse = V2ListTagsResponses[keyof V2ListTagsResponses];

export type V2CreateTagData = {
    body: TagCreate;
    path?: never;
    query?: never;
    url: '/v2/tags';
};

export type V2CreateTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2CreateTagError = V2CreateTagErrors[keyof V2CreateTagErrors];

export type V2CreateTagResponses = {
    /**
     * Document created, URL follows
     */
    201: Result;
};

export type V2CreateTagResponse = V2CreateTagResponses[keyof V2CreateTagResponses];

export type V2DeleteTagData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/v2/tags/{name}';
};

export type V2DeleteTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2DeleteTagError = V2DeleteTagErrors[keyof V2DeleteTagErrors];

export type V2DeleteTagResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type V2DeleteTagResponse = V2DeleteTagResponses[keyof V2DeleteTagResponses];

export type V2UpdateTagData = {
    body: TagUpdate;
    path: {
        name: string;
    };
    query?: never;
    url: '/v2/tags/{name}';
};

export type V2UpdateTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2UpdateTagError = V2UpdateTagErrors[keyof V2UpdateTagErrors];

export type V2UpdateTagResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TagPublic;
};

export type V2UpdateTagResponse = V2UpdateTagResponses[keyof V2UpdateTagResponses];

export type V2ListTagGroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/tags/groups';
};

export type V2ListTagGroupResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<TagGroupPublic>;
};

export type V2ListTagGroupResponse = V2ListTagGroupResponses[keyof V2ListTagGroupResponses];

export type V2DeleteFolderData = {
    body?: never;
    path: {
        folder_path: string;
    };
    query?: never;
    url: '/v2/folders/{folder_path}';
};

export type V2DeleteFolderErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type V2DeleteFolderError = V2DeleteFolderErrors[keyof V2DeleteFolderErrors];

export type V2DeleteFolderResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Result;
};

export type V2DeleteFolderResponse = V2DeleteFolderResponses[keyof V2DeleteFolderResponses];

export type V2GetFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/folders';
};

export type V2GetFoldersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: DirectorySummary;
};

export type V2GetFoldersResponse = V2GetFoldersResponses[keyof V2GetFoldersResponses];

export type V2GetWaifuScorerStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/statistics';
};

export type V2GetWaifuScorerStatisticsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<WaifuScoreResult>;
};

export type V2GetWaifuScorerStatisticsResponse = V2GetWaifuScorerStatisticsResponses[keyof V2GetWaifuScorerStatisticsResponses];
