export { createDb, resolveDbPath } from './connection.js'
export type { OpenOptions, PictoriaDatabase } from './connection.js'
export * as schema from './schema.js'
export { DOMINANT_COLOR_DIM, float32Blob, SIGLIP2_DIM } from './schema.js'
export { undeclaredTables, verifySchema } from './verify-schema.js'
export type { Mismatch } from './verify-schema.js'
export { listMigrations, runMigrations } from './migrate.js'
export { buildWhere, hasActiveFilters, BULK_UPDATABLE_FIELDS, GROUPABLE_COLUMNS, ORDERABLE_COLUMNS, UPDATABLE_FIELDS } from './filters.js'
export type { PostFilter, WhereParts } from './filters.js'
export { bucketCaseSql, SCORE_BUCKET_UNSCORED, SCORERS, SILVA, SILVA_LUNA, SILVA_SCORE_BUCKETS, WAIFU_SCORE_BUCKETS } from './scorers.js'
export type { Buckets, ScorerSpec } from './scorers.js'
export { waifuScoreDistribution } from './repositories/scores.js'
export type { WaifuBucketCount } from './repositories/scores.js'
export { addAgg, emptyAgg, folderScoreAggregates } from './repositories/folders.js'
export type { FolderScoreAgg } from './repositories/folders.js'
export { listTagGroups, listTagsWithCounts } from './repositories/tags.js'
export type { TagGroupRow, TagWithCount } from './repositories/tags.js'
export { aggregateStats, countByColumn, countByScorerBucket, countPosts } from './queries/counts.js'
export type { AggregateStats, BucketCount } from './queries/counts.js'
export { decodeDominantColor, fetchAestheticByIds, fetchColorsByIds, fetchTagsByIds, fetchWaifuByIds, getDetail, getGroupMembers, memberCounts, POST_COLUMNS, SIMPLE_BASE_COLUMNS, SIMPLE_POST_COLUMNS } from './queries/post-detail.js'
export type { AestheticScore, PostColor, PostDetail, PostTag, TagInfo } from './queries/post-detail.js'
export { buildSearchQuery, listPaginated, listSimpleByIdsPreservingOrder, searchPosts } from './queries/post-search.js'
export type { PaginatedPosts, PostFilterWithOrder } from './queries/post-search.js'
