export { createDb } from './connection.js'
export type { OpenOptions } from './connection.js'
export * as schema from './schema.js'
export { float32Blob, SIGLIP2_DIM } from './schema.js'
export { undeclaredTables, verifySchema } from './verify-schema.js'
export type { Mismatch } from './verify-schema.js'
export { listMigrations, runMigrations } from './migrate.js'
export { buildWhere, hasActiveFilters, BULK_UPDATABLE_FIELDS, GROUPABLE_COLUMNS, ORDERABLE_COLUMNS, UPDATABLE_FIELDS } from './filters.js'
export type { PostFilter, WhereParts } from './filters.js'
export { bucketCaseSql, SCORE_BUCKET_UNSCORED, SCORERS, SILVA, SILVA_LUNA, SILVA_SCORE_BUCKETS, WAIFU_SCORE_BUCKETS } from './scorers.js'
export type { Buckets, ScorerSpec } from './scorers.js'
export { waifuScoreDistribution } from './repositories/scores.js'
export type { WaifuBucketCount } from './repositories/scores.js'
export { addAgg, emptyAgg, folderScoreAggregates } from './repositories/folders.js'
export type { FolderScoreAgg } from './repositories/folders.js'
export { addTagToPost, createTag, deleteTag, deleteTags, getTag, getTagGroup, listTagGroups, listTagsWithCounts, removeTagFromPost, updateTagGroup } from './repositories/tags.js'
export type { TagGroupRow, TagRow, TagWithCount } from './repositories/tags.js'
export { aggregateStats, countByColumn, countByScorerBucket, countByTag, countPosts } from './queries/counts.js'
export type { AggregateStats, BucketCount, TagCount } from './queries/counts.js'
export { decodeDominantColor, fetchAestheticByIds, fetchColorsByIds, fetchTagsByIds, fetchWaifuByIds, getDetail, getGroupMembers, memberCounts, POST_COLUMNS, SIMPLE_BASE_COLUMNS, SIMPLE_POST_COLUMNS } from './queries/post-detail.js'
export type { AestheticScore, PostColor, PostDetail, PostTag, TagInfo } from './queries/post-detail.js'
export { buildSearchQuery, listPaginated, listSimpleByIdsPreservingOrder, searchByTextVector, searchPosts } from './queries/post-search.js'
export type { PaginatedPosts, PostFilterWithOrder } from './queries/post-search.js'
export { bulkUpdateField, clearCanonical, createPost, deleteManyReturningPaths, listIdsInFolder, makeCanonical, postExists, touchAccessed, updateField, updateForRotate } from './repositories/posts.js'
export { annotationTimeline, countPairwise, editAnnotation, insertAbsolute, insertContentFlag, insertPairwise, latestContentFlag, listAbsoluteForPost, listPairwiseForPost, markQueueItemDone, MUTABLE_KINDS, postsById, undoAnnotations } from './repositories/annotations.js'
export type { AbsoluteEventIn, PairwiseEventIn, QueueItemPost } from './repositories/annotations.js'
export { createAbsoluteQueue, createPairwiseQueue, listQueues, nextAbsoluteItems, nextPairwiseItems } from './repositories/annotation-queues.js'
export type { AnnotationQueueRow, QueueWithProgress } from './repositories/annotation-queues.js'
export { cosine, existingVectors, knn, SIGLIP2_TABLE, unitVectors, vectorExists } from './repositories/vectors.js'
export { PairGraph, Sampler, samplePairs, samplePostIds } from './repositories/sampling.js'
export type { Block } from './repositories/sampling.js'
export { aestheticWorkerKey, ensureCanonicalTagGroups, listBasicsPending, upsertBasics, fetchEmbeddingBlobs, listEmbeddingPending, listSilvaPending, listTaggerPending, listWaifuPending, notFailedClause, persistTaggerResults, ratingToInt, recordFailures, TAG_GROUP_COLORS, upsertAestheticScores, upsertVectors, upsertWaifuScores } from './repositories/backfill.js'
export type { BasicsPending, BasicsRowIn, PendingImage, TaggerRow } from './repositories/backfill.js'
export { assignFromPairs, exportVectorMatrix, replaceAllGroups } from './repositories/dedup.js'
export { getAestheticScore, getPostPath, getWaifuScore, isImagePath, persistAutoTagsForPost } from './repositories/commands.js'
export type { CommandPost } from './repositories/commands.js'
export { listImportedDanbooruIds, persistPostsWithTags } from './repositories/import-persist.js'
export type { NormalizedRow } from './repositories/import-persist.js'
