"""on update cascade

Revision ID: bb928e4c7a48
Revises: 6dbeb14619fb
Create Date: 2025-06-07 23:28:49.531101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb928e4c7a48'
down_revision: Union[str, None] = '6dbeb14619fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_has_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_has_tag_tag_name_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_has_tag_tag_name_tags'), 'tags', ['tag_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_has_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_has_tag_tag_name_tags'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_has_tag_tag_name_fkey'), 'tags', ['tag_name'], ['name'], ondelete='CASCADE')

    # ### end Alembic commands ###
