"""md5 to sha256

Revision ID: e8621e35996b
Revises: 2cb2fe7f0f5c
Create Date: 2025-08-24 03:41:03.332547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8621e35996b'
down_revision: Union[str, None] = '2cb2fe7f0f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_md5'))
        batch_op.drop_index(batch_op.f('idx_posts_created_at_desc'))

        # rename from md5 to sha256
        batch_op.alter_column('md5', new_column_name='sha256')
        
        batch_op.create_index('idx_posts_created_at_desc', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
        batch_op.create_index(batch_op.f('ix_posts_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_sha256'))
        batch_op.drop_index('idx_posts_created_at_desc', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
        
        batch_op.alter_column('md5', new_column_name='sha256')
        
        batch_op.create_index(batch_op.f('idx_posts_created_at_desc'), [sa.literal_column('created_at DESC')], unique=False) # type: ignore
        batch_op.create_index(batch_op.f('ix_posts_md5'), ['md5'], unique=False)


    # ### end Alembic commands ###
