"""add indexes for post_has_tag and post_has_color

Revision ID: 2cb2fe7f0f5c
Revises: 4a6d44b0aa23
Create Date: 2025-08-22 17:57:49.613003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb2fe7f0f5c'
down_revision: Union[str, None] = '4a6d44b0aa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_has_color', schema=None) as batch_op:
        batch_op.create_index('idx_post_has_color_post_id', ['post_id'], unique=False)

    with op.batch_alter_table('post_has_tag', schema=None) as batch_op:
        batch_op.create_index('idx_post_has_tag_post_id', ['post_id'], unique=False)
        batch_op.create_index('idx_post_has_tag_tag_name', ['tag_name'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_posts_created_at_desc', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_posts_created_at_desc', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})

    with op.batch_alter_table('post_has_tag', schema=None) as batch_op:
        batch_op.drop_index('idx_post_has_tag_tag_name')
        batch_op.drop_index('idx_post_has_tag_post_id')

    with op.batch_alter_table('post_has_color', schema=None) as batch_op:
        batch_op.drop_index('idx_post_has_color_post_id')

    # ### end Alembic commands ###
