"""add indexes for query optimization

Revision ID: 4a6d44b0aa23
Revises: bb928e4c7a48
Create Date: 2025-08-22 17:52:31.715063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6d44b0aa23'
down_revision: Union[str, None] = 'bb928e4c7a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_posts_file_path_created_at', ['file_path', 'created_at'], unique=False)
        batch_op.create_index('idx_posts_file_path_extension', ['file_path', 'extension'], unique=False)
        batch_op.create_index('idx_posts_file_path_pattern', ['file_path'], unique=False, postgresql_ops={'file_path': 'text_pattern_ops'})
        batch_op.create_index('idx_posts_file_path_rating', ['file_path', 'rating'], unique=False)
        batch_op.create_index('idx_posts_file_path_score', ['file_path', 'score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_posts_file_path_score')
        batch_op.drop_index('idx_posts_file_path_rating')
        batch_op.drop_index('idx_posts_file_path_pattern', postgresql_ops={'file_path': 'text_pattern_ops'})
        batch_op.drop_index('idx_posts_file_path_extension')
        batch_op.drop_index('idx_posts_file_path_created_at')

    # ### end Alembic commands ###
